FROM node:22-bookworm-slim
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --omit=dev && mkdir -p /app/data /app/backups && chown -R node:node /app
COPY --chown=node:node ./server ./server
COPY --chown=node:node ./scripts ./scripts
USER node
EXPOSE 3001
CMD ["node", "server/index.js"]